USE globetrek;

-- Packages
INSERT INTO packages (title, slug, description, short_description, duration_days, duration_nights, price, image, destination_category, price_range, is_featured) VALUES
('Island Escape', 'island-escape', 'Immerse yourself in the breathtaking beauty of Sri Lanka with our exclusive Island Escape package. Designed for thrill-seekers and nature lovers alike, this 5-day journey takes you from pristine beaches to lush tropical jungles. Experience local culture, wildlife encounters, and unparalleled relaxation in carefully selected accommodations.', 'Explore Sri Lanka pristine beaches and jungles on this 5-day adventure.', 5, 4, 75999.00, 'https://images.unsplash.com/photo-1734279135115-6d8984e08206?q=80&w=800&auto=format&fit=crop', 'Beaches & Coastal Getaways', '50000+', 1),
('Mountain Explorer', 'mountain-explorer', 'Embark on a 6-day trekking adventure through the misty hill country of Sri Lanka. From tea plantations to cloud forests, experience the island mountainous interior like never before.', 'Discover Sri Lanka lush hill country on this 6-day trekking adventure.', 6, 5, 65999.00, 'https://picsum.photos/seed/mountain/400/250', 'Hill Country & Nature', '50000+', 1),
('Beach Paradise', 'beach-paradise', 'Unwind on the sun-kissed shores of southern Sri Lanka. This 4-day getaway includes beach activities, water sports, and serene coastal relaxation.', 'Relax on pristine southern beaches with this 4-day coastal escape.', 4, 3, 39990.00, 'https://picsum.photos/seed/beach/400/250', 'Beaches & Coastal Getaways', '30000-49999', 1),
('Cultural Discovery', 'cultural-discovery', 'Dive deep into the rich cultural tapestry of Sri Lanka. Visit ancient temples, royal palaces, and UNESCO World Heritage sites across the cultural triangle.', 'Explore ancient temples and UNESCO sites on this 7-day cultural journey.', 7, 6, 55990.00, 'https://picsum.photos/seed/cultural/400/250', 'Cultural & Historical Sites', '50000+', 1),
('City Lights', 'city-lights', 'Experience the vibrant urban life of Colombo and surrounding cities. From bustling markets to modern skyline views, discover the dynamic side of Sri Lanka.', 'Experience the vibrant urban life of Colombo on this 3-day city break.', 3, 2, 35490.00, 'https://picsum.photos/seed/city/400/250', 'Urban & Cultural Capitals', '30000-49999', 0),
('Wild Safari', 'wild-safari', 'Get up close with Sri Lanka incredible wildlife. Visit Yala, Udawalawe, and other renowned national parks for unforgettable safari experiences.', 'Encounter Sri Lanka incredible wildlife on this 5-day safari adventure.', 5, 4, 82490.00, 'https://picsum.photos/seed/safari/400/250', 'Wildlife & National Parks', '50000+', 1);

-- Destinations
INSERT INTO destinations (name, slug, description, image, is_featured) VALUES
('Sigiriya Rock Fortress, Matale', 'sigiriya', 'A dramatic, UNESCO-protected ancient palace complex perched atop a massive 180-meter-high granite rock column. Built by King Kashyapa in the 5th century, it is famous for its colorful frescoes, graffiti-mirror wall, and monumental lion''s paw gateway.', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&h=400&fit=crop', 1),
('Galle Fort, Galle', 'galle', 'A living UNESCO World Heritage monument originally built by the Portuguese in 1588 and heavily fortified by the Dutch. Today, its atmospheric cobblestone streets are lined with beautifully preserved colonial villas, boutique cafes, and old churches, bounded by historic seaside ramparts.', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&h=400&fit=crop&crop=center', 1),
('Nine Arch Bridge (Elta), Badulla', 'nine-arch', 'An iconic, colonial-era railway bridge built completely out of brick, rock, and cement without using a single piece of steel. It stands hidden amid lush green tea plantations and misty mountains, drawing travelers who come to watch trains slowly pass over its line and admire arches.', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&h=400&fit=crop&crop=right', 0),
('Ancient City of Polonnaruwa, Polonnaruwa', 'polonnaruwa', 'Sri Lanka''s second ancient royal capital, active from the 10th to the 13th centuries. The vast, park-like archaeological site features marvelous preserved ruins, including the grand Royal Palace, massive stone stupas, and the famous Gal Vihara rock-cut Buddha statues.', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&h=400&fit=crop&crop=top', 0),
('Nuwara Eliya', 'nuwara-eliya', 'Famous dubbed "Little England," this high-altitude mountain station was favored by British colonizers for its cool climate. It is the premier destination for exploring manicured green tea estates, sprawling colonial-era bungalows, and dramatic waterfalls.', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&h=400&fit=crop&crop=bottom', 1),
('Mirissa, Matara', 'mirissa', 'A laid-back coastal paradise renowned as one of the best locations in the world for blue whale watching safaris. It is also widely visited for its crescent-shaped sandy beaches, vibrant beachside restaurants, and the iconic Coconut Turtle Hill viewpoint.', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&h=400&fit=crop&crop=center', 1);

-- Guides
INSERT INTO guides (name, specialty, region, description, image, profile_link, is_featured) VALUES
('Alex Rivera', 'Mountain Climbing & Hiking', 'Andes', 'Alex has over 15 years of experience leading expeditions across the Andes and the Himalayas. Passionate about safety and high-altitude endurance.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face', '#', 1),
('Mei Lin', 'Cultural Heritage & Photography', 'Southeast Asia', 'Specializing in deep-dive cultural tours across Southeast Asia. Mei provides unique photographic opportunities off the beaten path.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face', '#', 0),
('Samir Patel', 'Wildlife & Safari', 'Africa', 'An expert tracker and wildlife conservationist, Samir leads transformative safari experiences ensuring minimal ecological impact.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face', '#', 0),
('Elena Rossi', 'Culinary & Wine Tours', 'Europe', 'Born in Tuscany, Elena brings travelers into local kitchens and vineyards, offering an authentic taste of European gastronomic traditions.', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face', '#', 0),
('David Chen', 'Urban Exploration & Architecture', 'North America', 'David uncovers the hidden architectural marvels of the world''s most dense cities, contrasting modern skylines with historical roots.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face', '#', 0),
('Sarah Jenkins', 'Marine & Diving', 'Southeast Asia', 'A marine biologist turned guide, Sarah leads scuba and snorkeling trips focused on reef conservation and marine life education.', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face', '#', 0);

-- Accommodations
-- Transportations
INSERT INTO transportations (name, slug, description, short_description, location, vehicle_type, price_per_day, rating, image, has_ac, has_driver, has_insurance, is_available, is_featured) VALUES
('Colombo City Tuk-Tuk', 'colombo-city-tuk-tuk', 'A lively three-wheeler perfect for navigating Colombo bustling streets. Ideal for short trips, market visits, and exploring the city compact alleys with an experienced local driver.', 'Zippy three-wheeler for quick Colombo city trips with local driver.', 'Colombo', 'Three-Wheeler', 2500.00, 4.5, 'https://images.unsplash.com/photo-1586521995568-095a3c17fb89?w=600&h=400&fit=crop', 0, 1, 1, 1, 1),
('Kandy Hill Country Tuk', 'kandy-hill-country-tuk', 'Explore the scenic hill roads of Kandy in this comfortable three-wheeler. Perfect for visits to the Temple of the Tooth and surrounding tea gardens.', 'Comfortable tuk for scenic Kandy hill road exploration.', 'Kandy', 'Three-Wheeler', 3000.00, 4.3, 'https://images.unsplash.com/photo-1586521995568-095a3c17fb89?w=600&h=400&fit=crop&crop=center', 0, 1, 1, 1, 0),
('Galle Fort Explorer Tuk', 'galle-fort-explorer-tuk', 'Cruise along the southern coast in this vibrant tuk-tuk. From Galle Fort to Unawatuna beach, experience the best of the southern coastline.', 'Vibrant tuk for southern coast and Galle Fort exploration.', 'Galle', 'Three-Wheeler', 3500.00, 4.7, 'https://images.unsplash.com/photo-1586521995568-095a3c17fb89?w=600&h=400&fit=crop&crop=bottom', 0, 1, 1, 1, 1),
('Premium Sedan - Colombo', 'premium-sedan-colombo', 'A sleek, air-conditioned sedan for comfortable city travel and airport transfers. Spacious interior with luggage space, ideal for business travelers and families.', 'AC sedan for comfortable Colombo city and airport transfers.', 'Colombo', 'Car', 8500.00, 4.8, 'https://images.unsplash.com/photo-1549317661-bd32c8ce0afa?w=600&h=400&fit=crop', 1, 1, 1, 1, 1),
('Coastal Cruiser SUV', 'coastal-cruiser-suv', 'A robust SUV built for long-distance coastal drives. From Colombo to Galle, enjoy powerful AC, ample boot space, and a smooth ride on highway and beach roads.', 'Robust SUV for long-distance coastal highway drives.', 'Colombo', 'Car', 12000.00, 4.6, 'https://images.unsplash.com/photo-1549317661-bd32c8ce0afa?w=600&h=400&fit=crop&crop=right', 1, 1, 1, 1, 1),
('Hill Country Adventure SUV', 'hill-country-adventure-suv', 'A rugged 4x4 SUV designed for mountain terrain. Perfect for winding roads to Nuwara Eliya, Ella, and Horton Plains. Expert local drivers who know every bend.', 'Rugged 4x4 SUV for Sri Lanka mountain terrain adventures.', 'Nuwara Eliya', 'Car', 14000.00, 4.7, 'https://images.unsplash.com/photo-1549317661-bd32c8ce0afa?w=600&h=400&fit=crop&crop=top', 1, 1, 1, 1, 1),
('Sigiriya Trail Bike', 'sigiriya-trail-bike', 'A lightweight motorbike for adventurous solo travelers. Ride through paddy fields and villages to the majestic Sigiriya Rock Fortress. Helmet and insurance included.', 'Lightweight motorbike for Sigiriya trail adventures.', 'Sigiriya', 'Bike', 4500.00, 4.4, 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop', 0, 0, 1, 1, 0),
('Ella Gap Scenic Bike', 'ella-gap-scenic-bike', 'An off-road bike ready for the breathtaking Ella Gap. Navigate tea plantations and waterfalls with this well-maintained machine. Safety gear provided.', 'Off-road bike for breathtaking Ella Gap scenic routes.', 'Ella', 'Bike', 5000.00, 4.6, 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop&crop=center', 0, 0, 1, 1, 1),
('Family Minivan - 8 Seater', 'family-minivan-8-seater', 'A spacious 8-seater minivan perfect for family groups. Comfortable seating, large windows for sightseeing, and generous luggage space for multi-day tours.', 'Spacious 8-seater minivan for family group tours.', 'Colombo', 'Minivan', 15000.00, 4.8, 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600&h=400&fit=crop', 1, 1, 1, 1, 1),
('Airport Transfer Minivan', 'airport-transfer-minivan', 'Reliable minivan for airport pickups and drop-offs. Fits 6 passengers with full luggage. Meet-and-greet service with name board, water bottles, and Wi-Fi.', 'Reliable airport transfer minivan with meet-and-greet service.', 'Colombo', 'Minivan', 10000.00, 4.5, 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600&h=400&fit=crop&crop=right', 1, 1, 1, 1, 0);

-- Accommodations
('The Azure Villa', 'azure-villa', 'A stunning cliffside villa overlooking the Aegean Sea in Santorini. Featuring private infinity pool, sun terrace, and breathtaking sunset views. Perfect for romantic getaways and luxury retreats.', 'Cliffside luxury villa with private infinity pool and Aegean Sea views.', 'Santorini, Greece', 'Villa', 350.00, 4.9, 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=600&h=400&fit=crop', 1, 1, 1, 1, 0, 1),
('Alpine Eco Lodge', 'alpine-eco-lodge', 'A sustainable mountain lodge nestled in the Swiss Alps. Powered by renewable energy, offering farm-to-table dining, guided hiking excursions, and panoramic mountain views from every room.', 'Sustainable mountain lodge with farm-to-table dining in the Swiss Alps.', 'Swiss Alps, Switzerland', 'Boutique', 210.00, 4.7, 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&h=400&fit=crop', 1, 0, 0, 1, 0, 1),
('Urban Minimalist Hotel', 'urban-minimalist-hotel', 'A sleek, design-forward hotel in the heart of Tokyo. Clean lines, smart-room technology, and a rooftop bar with skyline views. Steps from Shibuya Crossing and top-rated restaurants.', 'Design-forward hotel in central Tokyo with smart-room technology.', 'Tokyo, Japan', 'Hotel', 180.00, 4.5, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop', 1, 0, 0, 1, 1, 0),
('Coral Bay Resort', 'coral-bay-resort', 'An expansive beachfront resort on the Maldivian islands. Private overwater bungalows, world-class diving center, infinity pool, and full-service spa. The ultimate tropical escape.', 'Private overwater bungalows with diving center and full-service spa.', 'Malé, Maldives', 'Resort', 520.00, 4.8, 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&h=400&fit=crop', 1, 1, 1, 1, 1, 1),
('Heritage Boutique Inn', 'heritage-boutique-inn', 'A restored colonial-era boutique inn in the heart of Galle Fort. Antiques, courtyard garden, and personalized concierge service. Walk to cobblestone streets, cafes, and the ramparts.', 'Restored colonial inn in Galle Fort with courtyard garden.', 'Galle, Sri Lanka', 'Boutique', 135.00, 4.6, 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&h=400&fit=crop', 1, 0, 0, 1, 0, 1),
('Safari Tented Camp', 'safari-tented-camp', 'Luxury tented accommodation on the edge of Yala National Park. Wake to wildlife sounds, enjoy bush dinners under the stars, and embark on guided safari drives at dawn.', 'Luxury tents on the edge of Yala National Park with safari drives.', 'Yala, Sri Lanka', 'Resort', 275.00, 4.7, 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=600&h=400&fit=crop', 1, 0, 0, 1, 0, 0);
